/**
 * Cubic spaces: the flat cube and three compact flat 3-manifolds built from an N×N×N block.
 *
 * ## Quotient spaces E³/Γ
 *
 * Each wrapped space is the quotient of Euclidean space by a group Γ of rigid motions acting
 * freely. In cell coordinates the universal cover is the lattice Z³, and the block
 * [0,N)³ is a fundamental domain. Γ is generated by
 *
 * - the translations x ↦ x + N and y ↦ y + N (so x and y always wrap like a torus), and
 * - one *z-gluing* γ that identifies the top face z = N with the bottom face z = 0 after
 *   applying a planar map G to (x, y): the point (x, y, z + N) is the same as (G(x, y), z).
 *
 * | space        | G(x, y)          | holonomy                     | orientable |
 * |--------------|------------------|------------------------------|------------|
 * | `torus3`     | (x, y)           | trivial                      | yes        |
 * | `tetracosm`  | (N−1−y, x)       | Z/4, quarter turn about z    | yes        |
 * | `amphicosm1` | (N−1−x, y)       | Z/2, reflection in x         | no         |
 *
 * The rotation and the reflection act about the center of the square, so they map cell centers
 * to cell centers (hence the `N−1` instead of `N`).
 *
 * All motions in Γ are isometries, so every point has a neighborhood that looks exactly like
 * ordinary space: these manifolds are **flat** (zero curvature everywhere). What changes is the
 * global topology. The *holonomy* is what happens to a direction carried once around a loop:
 * crossing the z-seam applies the linear part of G to the direction, so in the tetracosm a
 * walker going "up" comes back rotated by 90°, and in the amphicosm comes back mirrored (which
 * is why that space is non-orientable: a right hand returns as a left hand).
 *
 * Straight lines (geodesics) of the quotient are images of straight lines of the cover. This is
 * what makes {@link CubicQuotient.reduce} the single source of truth: stepping is just
 * "add d in the cover, then reduce".
 *
 * The `flat` space is the plain bounded cube [0,N)³ (classic 3D tic-tac-toe): any step that
 * leaves the block is blocked.
 */
import { DIRECTIONS_3D, dir3 } from './directions';
import { assertCell, assertSize, mod } from './math';
import type { CellId, Dir, Layout2D, StepResult, Topology, TopologyId } from './types';

export type CubicTopologyId = Exclude<TopologyId, 'tesseract'>;

/** An affine map p ↦ m·p + t on Z³. `m` is a 3×3 integer matrix in row-major order. */
export interface Affine3 {
  readonly m: readonly number[];
  readonly t: readonly number[];
}

/** Apply an affine map to a point. */
export function applyAffine(A: Affine3, p: readonly number[]): number[] {
  return [0, 1, 2].map((r) => applyRow(A.m, r, p) + (A.t[r] as number));
}

/** Apply only the linear part of an affine map (how it acts on direction vectors). */
export function applyLinear(A: Affine3, v: readonly number[]): number[] {
  return [0, 1, 2].map((r) => applyRow(A.m, r, v));
}

/** The composition A ∘ B (apply B first, then A). */
export function composeAffine(A: Affine3, B: Affine3): Affine3 {
  const m: number[] = [];
  for (let r = 0; r < 3; r++) {
    for (let c = 0; c < 3; c++) {
      m.push(applyRow(A.m, r, [B.m[c] as number, B.m[3 + c] as number, B.m[6 + c] as number]));
    }
  }
  return { m, t: applyAffine(A, B.t) };
}

function applyRow(m: readonly number[], r: number, v: readonly number[]): number {
  let sum = 0;
  for (let c = 0; c < 3; c++) sum += (m[3 * r + c] as number) * (v[c] as number);
  return sum;
}

const IDENTITY: Affine3 = { m: [1, 0, 0, 0, 1, 0, 0, 0, 1], t: [0, 0, 0] };

/**
 * A planar affine map (x, y) ↦ (a·x + b·y + e, c·x + d·y + f), stored as [a, b, c, d, e, f].
 * Used for the z-gluing G and its inverse.
 */
type PlaneMap = readonly [number, number, number, number, number, number];

interface Gluing {
  /** G: applied to (x, y) and (dx, dy) when a step leaves through the top (z ≥ N). */
  readonly up: PlaneMap;
  /** G⁻¹: applied when a step leaves through the bottom (z < 0). */
  readonly down: PlaneMap;
}

function gluingFor(id: CubicTopologyId, n: number): Gluing | null {
  const k = n - 1;
  switch (id) {
    case 'flat':
      return null;
    case 'torus3':
      return { up: [1, 0, 0, 1, 0, 0], down: [1, 0, 0, 1, 0, 0] };
    case 'tetracosm':
      // Quarter turn about the square's center: (x, y) ↦ (N−1−y, x), and back.
      return { up: [0, -1, 1, 0, k, 0], down: [0, 1, -1, 0, 0, k] };
    case 'amphicosm1':
      // Mirror in the plane x = (N−1)/2. A reflection is its own inverse.
      return { up: [-1, 0, 0, 1, k, 0], down: [-1, 0, 0, 1, k, 0] };
  }
}

/** Lift a planar map to the 3D screw/glide motion (x, y, z) ↦ (g(x, y), z + dz). */
function liftPlaneMap(g: PlaneMap, dz: number): Affine3 {
  const [a, b, c, d, e, f] = g;
  return { m: [a, b, 0, c, d, 0, 0, 0, 1], t: [e, f, dz] };
}

/**
 * The flat cube, the 3-torus, the tetracosm, or the first amphicosm, on an N×N×N block of cells.
 *
 * Cell `c = x + N·(y + N·z)`, with x, y, z in [0, N). The local frame of every cell is the
 * frame of the fundamental domain, so all cells share the same 26 directions.
 *
 * N ≥ 3 is recommended. At N = 2 the steps +1 and −1 reach the same cell, which is still
 * handled correctly (lines with a repeated cell are rejected and duplicates are merged).
 */
export class CubicQuotient implements Topology {
  readonly id: CubicTopologyId;
  readonly n: number;
  readonly cellCount: number;
  readonly dim = 3 as const;
  readonly panelCount: number;
  private readonly gluing: Gluing | null;

  constructor(id: CubicTopologyId, n: number) {
    assertSize(n, 1);
    this.id = id;
    this.n = n;
    this.cellCount = n * n * n;
    this.panelCount = n;
    this.gluing = gluingFor(id, n);
  }

  /** True for the closed manifolds (every step succeeds), false for the bounded flat cube. */
  get wrapped(): boolean {
    return this.gluing !== null;
  }

  localDirections(c: CellId): readonly Dir[] {
    assertCell(c, this.cellCount);
    return DIRECTIONS_3D;
  }

  step(c: CellId, d: Dir): StepResult | null {
    assertCell(c, this.cellCount);
    const [dx, dy, dz] = checkDir3(d);
    const n = this.n;
    return this.reduceXYZ(
      (c % n) + dx,
      (Math.floor(c / n) % n) + dy,
      Math.floor(c / (n * n)) + dz,
      dx,
      dy,
      dz,
    );
  }

  /**
   * Map a point `p` of the universal cover Z³, carrying direction `d`, to the cell it represents
   * and the direction as seen in that cell's local frame. Returns `null` only for the flat cube
   * when `p` is outside the block.
   *
   * This is the canonical projection Z³ → Z³/Γ. `step(c, d)` equals `reduce(coords(c) + d, d)`,
   * and k steps along a straight line equal `reduce(coords(c) + k·d, d)`.
   */
  reduce(p: readonly number[], d: Dir): StepResult | null {
    const [x, y, z] = checkDir3(p);
    const [dx, dy, dz] = checkDir3(d);
    return this.reduceXYZ(x, y, z, dx, dy, dz);
  }

  private reduceXYZ(
    x: number,
    y: number,
    z: number,
    dx: number,
    dy: number,
    dz: number,
  ): StepResult | null {
    const n = this.n;
    const g = this.gluing;
    if (g === null) {
      if (x < 0 || x >= n || y < 0 || y >= n || z < 0 || z >= n) return null;
      return { cell: x + n * (y + n * z), dir: dir3(dx, dy, dz) };
    }
    x = mod(x, n);
    y = mod(y, n);
    // Each time we cross the top face (wrap z down by N) apply G; each bottom crossing applies G⁻¹.
    // G permutes the cells of the N×N square, so (x, y) stays in range without another mod.
    const layers = Math.floor(z / n);
    const map = layers > 0 ? g.up : g.down;
    for (let i = Math.abs(layers); i > 0; i--) {
      const [m00, m01, m10, m11, tx, ty] = map;
      [x, y] = [m00 * x + m01 * y + tx, m10 * x + m11 * y + ty];
      [dx, dy] = [m00 * dx + m01 * dy, m10 * dx + m11 * dy];
    }
    z -= layers * n;
    return { cell: x + n * (y + n * z), dir: dir3(dx, dy, dz) };
  }

  /**
   * The deck transformation for cover offset (i, j, k): the element of Γ that carries the
   * fundamental domain to the copy that sits i blocks along x, j along y and k along z.
   *
   * It is T(N·i, N·j, 0) ∘ S^k, where S(x, y, z) = (G⁻¹(x, y), z + N) is the screw motion
   * (tetracosm), glide reflection (amphicosm) or plain translation (3-torus). For every cell
   * coordinate q and direction d, `reduce(applyAffine(D, q), applyLinear(D, d))` returns the cell
   * at q with direction d, i.e. the ghost copy is a faithful picture of the same cell.
   *
   * Maps act on integer cell coordinates. For rendering at centered positions (q + ½ − N/2),
   * conjugate by that shift: then the linear part is a pure rotation/reflection about the z-axis.
   *
   * The flat cube has no deck group, so only (0, 0, 0) is allowed there.
   */
  deckTransform(i: number, j: number, k: number): Affine3 {
    const g = this.gluing;
    if (g === null) {
      if (i !== 0 || j !== 0 || k !== 0) {
        throw new RangeError('The flat cube is simply connected and has no deck transformations.');
      }
      return IDENTITY;
    }
    const n = this.n;
    const screw = k > 0 ? liftPlaneMap(g.down, n) : liftPlaneMap(g.up, -n);
    let deck: Affine3 = { m: IDENTITY.m, t: [n * i, n * j, 0] };
    for (let r = Math.abs(k); r > 0; r--) deck = composeAffine(deck, screw);
    return deck;
  }

  coords(c: CellId): readonly number[] {
    assertCell(c, this.cellCount);
    const n = this.n;
    return [c % n, Math.floor(c / n) % n, Math.floor(c / (n * n))];
  }

  cellAt(coords: readonly number[]): CellId {
    const [x, y, z] = checkDir3(coords);
    const n = this.n;
    if ([x, y, z].some((v) => !Number.isInteger(v) || v < 0 || v >= n)) {
      throw new RangeError(`No cell at (${coords.join(', ')}).`);
    }
    return x + n * (y + n * z);
  }

  /** Slice view: panel = z, row = y, col = x. */
  layout2D(c: CellId): Layout2D {
    assertCell(c, this.cellCount);
    const n = this.n;
    return { panel: Math.floor(c / (n * n)), row: Math.floor(c / n) % n, col: c % n };
  }
}

function checkDir3(v: readonly number[]): readonly [number, number, number] {
  if (v.length !== 3) throw new RangeError(`Expected a 3D vector, got length ${v.length}.`);
  return v as unknown as readonly [number, number, number];
}
